apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: aap-pdfgen-alerts
  labels:
    team: aap
    app: aap-pdfgen
  namespace: aap
spec:
  receivers:
    slack:
      channel: '#aap-github'
  alerts:
    - alert: aap-pdfgen-app-nede
      expr: kube_deployment_status_replicas_unavailable{deployment="soknad-api",job="kubernetes-service-endpoints"} > 0
      for: 5m
      description: "pdfgen har utilgjengelige podder i aap"
      action: "kubectl describe pod -l app=pdfgen -n aap` for events og `kubectl get pods -l app=pdfgen -n aap` for å se feilende podder"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: aap-pdfgen-kontinuerlig-restart
      expr: sum(increase(kube_pod_container_status_restarts_total{container=~"pdfgen"}[5m])) by (container) > 2
      for: 2m
      description: "pdfgen har restartet flere ganger de siste 5 minuttene!"
      action: "Se `kubectl describe pod pdfgen` for events, og `kubectl logs pdfgen` for logger"
      sla: respond within 1h, during office hours
      severity: danger