apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pdfgen
  namespace: aap
  labels:
    team: aap
spec:
  accessPolicy:
    inbound:
      rules:
        - application: soknad-api
        - application: soknad-konsument

  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_ready
  prometheus:
    enabled: true
    path: /prometheus