apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pdfgen
  namespace: aap
  labels:
    team: aap
spec:
  accessPolicy:
    inbound:
      rules:
        - application: innsending
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 2048Mi
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_ready
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki      
