name: Manual deploy to dev environment
on:
  workflow_dispatch:

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/aap-pdfgen:${{ github.sha }}

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --pull --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
  deploy_to_dev:
    name: Deploy to dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v3
      -   uses: nais/deploy/actions/deploy@v1
          env:
            APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
            CLUSTER: dev-gcp
            RESOURCE: nais.yaml