name: Build and deploy to dev

on:
  push:
    branches:
      - master

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    IMAGE_BASE: ghcr.io/${{ github.repository }}
    APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
    RESOURCE: nais.yaml
    PRINT_PAYLOAD: true

jobs:
   bygg:
      runs-on: ubuntu-latest
      outputs:
          image: ${{ steps.build.outputs.image }}
      steps:
        - uses: actions/checkout@v4
        - name: Setter tag-navn
          run: echo "TAG=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

        - name: Setter image-navn
          run: echo "IMAGE=$(echo $IMAGE_BASE):$(echo $TAG)" >> $GITHUB_ENV

        - name: Bygg og push Docker image
          id: build
          run: |
            echo "::set-output name=image::${{ env.IMAGE }}"
            docker build --pull --tag ${IMAGE} .
            echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
            docker push ${IMAGE}

   deploy:
       strategy:
           matrix:
               cluster: [ dev-gcp,prod-gcp ]
       environment: ${{ matrix.cluster }}:aap
       name: Deploy til ${{ matrix.cluster }}
       needs: bygg
       runs-on: ubuntu-latest
       env:
           CLUSTER: ${{ matrix.cluster }}
           IMAGE: ${{needs.bygg.outputs.image}}
           RESOURCE: ./${{matrix.cluster}}-alerts.yaml
       steps:
           - uses: actions/checkout@v4
           - uses: nais/deploy/actions/deploy@master