name: Deploy to Dev And Prod
on:
  workflow_dispatch:
    inputs:
      cluster:
        description: Cluster
        required: true
        default: dev-gcp
        type: choice
        options:
          - dev-gcp
          - prod-gcp
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**'

jobs:
  build:
    if: github.event.pull_request.merged || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      actions: read
      checks: write
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push docker image to GAR and sign image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: aap
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}


  deploy_to_dev:
    name: Deploy to dev
    if: github.event.pull_request.merged || github.event_name == 'push' || github.event.inputs.cluster == 'dev-gcp'
    permissions:
      contents: read
      id-token: write
    needs: build
    uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      cluster: dev-gcp
      manifest: nais.yaml

  deploy_to_prod:
    name: Deploy to prod
    if: github.event.pull_request.merged || github.event_name == 'push' || github.event.inputs.cluster == 'prod-gcp'
    permissions:
      contents: read
      id-token: write
    needs: build
    uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      cluster: prod-gcp
      manifest: nais.yaml
